version: '3.8'

services:
  tg-spider:
    build: .
    container_name: tg-session
    network_mode: bridge
    ports:
      - "8899:8899"
    volumes:
      - /vol1/1000/docker/tg-session/sessions:/app/sessions  
    restart: unless-stopped
    environment:
      - TG_LANG=zh